import { Staff, Event, DispatchRequest, ChatMessage } from '@/types';

export const mockStaff: Staff[] = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Martinez',
    role: 'staff',
    staffRoles: ['bartender', 'server'],
    city: 'San Francisco',
    status: 'available',
    phone: '(555) 123-4567',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    email: 'sarah@example.com',
    name: 'Sarah Chen',
    role: 'staff',
    staffRoles: ['server', 'coordinator'],
    city: 'San Francisco',
    status: 'assigned',
    phone: '(555) 234-5678',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    email: 'mike@example.com',
    name: 'Mike Johnson',
    role: 'staff',
    staffRoles: ['kitchen'],
    city: 'Oakland',
    status: 'available',
    phone: '(555) 345-6789',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    email: 'emily@example.com',
    name: 'Emily Davis',
    role: 'staff',
    staffRoles: ['bartender'],
    city: 'San Jose',
    status: 'unavailable',
    phone: '(555) 456-7890',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: '5',
    email: 'alex@example.com',
    name: 'Alex Rivera',
    role: 'staff',
    staffRoles: ['security', 'coordinator'],
    city: 'San Francisco',
    status: 'available',
    phone: '(555) 567-8901',
    createdAt: new Date('2024-04-01'),
  },
  {
    id: '6',
    email: 'lisa@example.com',
    name: 'Lisa Wong',
    role: 'staff',
    staffRoles: ['server', 'bartender'],
    city: 'San Francisco',
    status: 'available',
    phone: '(555) 678-9012',
    createdAt: new Date('2024-05-15'),
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Corporate Holiday Party',
    description: 'Annual holiday celebration for TechCorp',
    date: new Date('2025-12-28'),
    startTime: '18:00',
    endTime: '23:00',
    location: 'The Grand Ballroom, 123 Market St',
    city: 'San Francisco',
    clientId: 'client-1',
    vendorId: 'vendor-1',
    createdBy: 'admin-1',
    createdAt: new Date('2024-12-01'),
    status: 'open',
    roleRequirements: [
      { role: 'bartender', quantity: 2, filled: 1, pending: 0 },
      { role: 'server', quantity: 4, filled: 1, pending: 1 },
      { role: 'kitchen', quantity: 1, filled: 0, pending: 0 },
    ],
  },
  {
    id: '2',
    title: 'New Year Gala',
    description: 'Exclusive NYE celebration',
    date: new Date('2025-12-31'),
    startTime: '20:00',
    endTime: '02:00',
    location: 'Skyline Rooftop, 456 Mission St',
    city: 'San Francisco',
    clientId: 'client-2',
    createdBy: 'admin-1',
    createdAt: new Date('2024-12-10'),
    status: 'open',
    roleRequirements: [
      { role: 'bartender', quantity: 3, filled: 0, pending: 1 },
      { role: 'server', quantity: 6, filled: 0, pending: 0 },
      { role: 'security', quantity: 2, filled: 0, pending: 0 },
    ],
  },
  {
    id: '3',
    title: 'Private Dinner',
    description: 'Intimate dinner party for 20 guests',
    date: new Date('2025-01-05'),
    startTime: '19:00',
    endTime: '22:00',
    location: 'Private Residence, Oakland Hills',
    city: 'Oakland',
    clientId: 'client-3',
    createdBy: 'admin-1',
    createdAt: new Date('2024-12-15'),
    status: 'draft',
    roleRequirements: [
      { role: 'kitchen', quantity: 1, filled: 0, pending: 0 },
      { role: 'server', quantity: 2, filled: 0, pending: 0 },
    ],
  },
];

export const mockDispatchRequests: DispatchRequest[] = [
  { id: '1', eventId: '1', staffId: '1', staffRole: 'bartender', status: 'accepted', sentAt: new Date('2024-12-20'), respondedAt: new Date('2024-12-20') },
  { id: '2', eventId: '1', staffId: '2', staffRole: 'server', status: 'accepted', sentAt: new Date('2024-12-20'), respondedAt: new Date('2024-12-20') },
  { id: '3', eventId: '1', staffId: '5', staffRole: 'coordinator', status: 'pending', sentAt: new Date('2024-12-21') },
  { id: '4', eventId: '2', staffId: '1', staffRole: 'bartender', status: 'pending', sentAt: new Date('2024-12-22') },
  { id: '5', eventId: '2', staffId: '3', staffRole: 'kitchen', status: 'declined', sentAt: new Date('2024-12-22'), respondedAt: new Date('2024-12-22') },
];

export const mockMessages: ChatMessage[] = [
  { id: '1', eventId: '1', senderId: 'admin-1', senderName: 'Matthew', content: 'Welcome to the event chat! Please confirm your arrival time.', createdAt: new Date('2024-12-20T10:00:00') },
  { id: '2', eventId: '1', senderId: '1', senderName: 'John Martinez', content: 'I\'ll be there at 5:30 PM for setup.', createdAt: new Date('2024-12-20T10:15:00') },
  { id: '3', eventId: '1', senderId: '2', senderName: 'Sarah Chen', content: 'Same here, arriving at 5:30.', createdAt: new Date('2024-12-20T10:20:00') },
  { id: '4', eventId: '1', senderId: 'vendor-1', senderName: 'TechCorp Events', content: 'Great! The venue will be ready by 5 PM.', createdAt: new Date('2024-12-20T10:25:00') },
];
